name: first project devops

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du repository
    - name: Checkout du repository
      uses: actions/checkout@v2

    # Build et run du Docker containers
    - name: Build et run du Docker containers
      run: |
        docker-compose up --build -d
      working-directory: ./my_first_project

    # Déploiement
    - name: Déploiement
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PATH }}
        publish_dir: ./my_first_project
        
